-- CreateTable
CREATE TABLE "RFID" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "rfid" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "lastTimeUsed" DATETIME NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "RFID_rfid_key" ON "RFID"("rfid");
